### ISSUE TITLE
I have te error

### ISSUE THREAD

**Issue by mateusgalasso** [thehung111/iosAndroidDBCodeGenerator#1]
Error: %1 is not a valid Win32 application.
C:\Users\Mateus\myapp\node_modules\sqlite3\build\Release\node_sqlite3.node
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Mateus\myapp\node_modules\sqlite3\lib\sqlite
3.js:1:104)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by thehung111** [comment]
it worked fine on my Macbook Pro. I think it might be a problem in the sqlite version. Maybe you can try to delete the node_modules folder and reinstall the dependencies with npm. 

I have not updated the code in a long time also :) there are some bug fixes which I have not committed also.
