### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by salismt** [thehung111/iosAndroidDBCodeGenerator#2]
when I do node app.js the app won't run with this error

```
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/salis/Documents/Learn/Javascript/iosAndroidDBCodeGenerator/node_modules/sqlite3/lib/sqlite3.js:1:104)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

```

**Comment by thehung111** [comment]
You can try to delete the node_modules folder and re-install the dependencies. I used it on my Macbook so it might be different. It should be working.
